#!/bin/bash
# try to reinstall
# sudo apt install --reinstall bluez gnome-bluetooth indicator-bluetooth pulseaudio-module-bluetooth
# sudo apt-get install blueman 
# sudo systemctl start bluetooth.service

# enable blouetooth in pop os src: https://askubuntu.com/questions/1403817/i-cant-turn-on-bluetooth-in-ubuntu-22-04-lts
sudo rfkill unblock all 
sudo hciconfig hci0 down
sudo rmmod btusb
sudo modprobe btusb
sudo hciconfig hci0 up
